version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.3.2
  node: circleci/node@7.1.0

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  deploy:
    executor: node/default
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal:
          azure-sp: AZURE_CLIENT_ID
          azure-sp-password: AZURE_CLIENT_SECRET
          azure-sp-tenant: AZURE_TENANT_ID

      - run:
          name: Set subscription
          command: |
            az account set --subscription $AZURE_SUBSCRIPTION_ID

      - run:
          name: Zip app and deploy
          command: |
            zip -r app.zip . -x "*.git*" "node_modules/*"
            az webapp deploy \
              --resource-group $AZURE_RG \
              --name $AZURE_APP_NAME \
              --src-path app.zip \
              --type zip

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
